# Generated by Django 3.1.3 on 2020-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201130_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phoneOtp',
            field=models.IntegerField(default=0),
        ),
    ]
