# Generated by Django 3.1.3 on 2020-12-12 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='address',
            new_name='deliverAddress',
        ),
    ]
