# Generated by Django 3.1.3 on 2020-11-29 19:56

import accounts.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='aadhar',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='aadhaar',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True, validators=[accounts.validators.validate_aadhaar]),
            preserve_default=False,
        ),
    ]
