# Generated by Django 3.1.3 on 2020-11-30 03:56

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20201130_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/avatar.png', upload_to=store.models.upload_image_path),
        ),
    ]
