# Generated by Django 3.1.3 on 2020-12-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shippingaddress_active'),
        ('store', '0010_customer_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Available', max_length=50)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.shippingaddress')),
            ],
        ),
    ]
