# Generated by Django 3.1.3 on 2020-11-30 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201127_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/<function upload_image_path at 0x7fc208c349d0>'),
        ),
    ]
