# Generated by Django 3.1.3 on 2020-12-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
