# Generated by Django 3.1.3 on 2020-11-30 03:48

from django.db import migrations, models
import products.imagepath


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201130_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.imagepath.upload_image_path),
        ),
    ]
