# Generated by Django 3.1.3 on 2020-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201129_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_staff',
            field=models.BooleanField(default=False),
        ),
    ]
