# Generated by Django 3.1.3 on 2020-11-29 04:33

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201128_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhaar',
            field=models.IntegerField(unique=True, validators=[accounts.validators.validate_aadhaar]),
        ),
    ]
