# Generated by Django 3.1.3 on 2020-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shippingaddress_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
